---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: repo
  label: Repo
  type: text
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: weight
  label: Weight
  type: text
  hidden: false
  default: 0
- name: type
  label: Type
  type: text
  hidden: false
  default: ''
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
